const artists = [
    {
        id: 1,
        name: 'Юрий Альберт',
        direction: 'Московский концептуализм, текст, институциональная критика',
        image: 'https://artuzel.com/sites/default/files/styles/large/public/yu_albert_0.jpg?itok=6NDMdFtj',
        bio: 'Юрий Альберт — один из ключевых представителей «новой волны» московского концептуализма 1980-х годов. Его художественная практика сосредоточена на исследовании фундаментальных вопросов современного искусства: что является искусством и кем является художник в системе культурного производства. Работая с иронией, парадоксом и редукцией визуального языка, Альберт обращается к истории искусства как к открытому архиву, свободно переосмысливая канонические образы и художественные клише. Его проекты часто построены на отрицании, цитировании и доведении до абсурда устоявшихся представлений об авторстве и художественной ценности.',
        concept:
            'Использую язык отрицания, иронии и минимализма. Работаю с текстом, символом и историей искусства как системой знаков, подвергая сомнению само понятие художественного высказывания.',
        portfolio: [
            {
                title: 'Я не Джаспер Джонс',
                image: 'https://static.dzeninfra.ru/s3/zen-apps/desktop2/3.399.1/s2L8dMk/AKQ12n5306e8b78ABdLUzKEiRgm2vdjXmYQt6pXTaN4NGsBoSUuOUsQpDUoP3q4m4oBvSMwXmmh2pIRg7IsJ0t6jwTbh9xkbX8ITg6cVUoX4tDl3PvWnQK8ACuHoaA0AWaAKlHpDJpLTn4fd0C48HrN65CRiUrUVpZ2iQthBuhIpR7aNbVDcE3uRVbOG8CiXE8NJsITrDsOPi4FmJiwI9GO5MqjyCy4VjXVeEaKRrJw1o3ldl7nx2i',
                year: 1980,
            },
            {
                title: 'Основные краски',
                image: 'https://avatars.dzeninfra.ru/get-zen_doc/1875669/pub_6233a8ffdaa2462fb7dfb035_6233a901f04ffa02a8eb9114/scale_1200',
                year: 1987,
            },
            {
                title: 'Я не Казимир Малевич',
                image: 'https://i.pinimg.com/736x/c5/c5/55/c5c555626b8437b1a8cfe4d49e9c231c.jpg',
                year: 1981,
            },
        ],
    },
    {
        id: 2,
        name: 'Евгений Антуфьев',
        direction: 'Объект, инсталляция, архаика, мифология',
        image: 'https://artlogic-res.cloudinary.com/w_1200,c_limit,f_auto,fl_lossy,q_auto/ws-artlogicwebsite2263/usr/images/artists/artist_image/items/34/345e1321c7b04220a140a9d97962b467/antufievportrait.jpg?focal=48,25',
        bio: 'Евгений Антуфьев — художник родом из Тувы, чья карьера стремительно началась в начале 2010-х годов. Уже в 23 года он был отмечен кураторским сообществом Москвы и удостоен звания лучшего молодого художника по версии Премии Кандинского. Антуфьев быстро вышел на международную сцену, участвуя в крупных европейских проектах, включая биеннале Manifesta в Цюрихе. Его искусство опирается на синтез личного культурного опыта, шаманских практик и переосмысленных архаических мифов.',
        concept:
            'Работаю с материалами как носителями магического и ритуального смысла, актуализируя древние символы в современном художественном контексте.',
        portfolio: [
            {
                title: 'Двенадцать, дерево, дельфин…',
                image: 'https://avatars.dzeninfra.ru/get-zen_doc/4759087/pub_6233a8ffdaa2462fb7dfb035_6233a90138571e029270cf06/scale_1200',
                year: 2014,
            },
            {
                title: 'Исследование материалов',
                image: 'https://avatars.dzeninfra.ru/get-zen_doc/5231507/pub_6233a8ffdaa2462fb7dfb035_6233a901164da772a6216b45/scale_1200',
                year: 2014,
            },
        ],
    },
    {
        id: 3,
        name: 'Дмитрий Аске',
        direction: 'Стрит-арт, объект, рельеф',
        image: 'https://thecity.m24.ru/b/d/SYketSive4E_JvbObLLBFlFNGhtudTX-kYVfOS8Xp1Gj5pqKzWTJSFS-PsArI08gRZaK1yZktQXWesHOaOz7FWcJ5xZMng=iITpHF500yoaiV0XnAAONQ.jpg',
        bio: 'Дмитрий Аске начал карьеру в 2000-х годах как граффити-художник. Со временем его практика эволюционировала от уличных работ к крупноформатным скульптурам и галерейным объектам. Он реализовал масштабные муралы в России и Европе, а также сотрудничал с международными брендами, включая Nike и Sony.',
        concept:
            'Создаю многослойные структуры, соединяя уличную эстетику с архитектурной логикой и дизайнерским мышлением.',
        portfolio: [
            {
                title: 'День и ночь',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnlutV14tOTkFiwatZmJN1VwyNO60yLop2sw&s',
                year: 2016,
            },

            {
                title: 'Монументальные муралы',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeZOnV0NcjkzcHKu62BrmUJeEo3uvfxe8y7A&s',
                year: 2018,
            },
        ],
    },
    {
        id: 4,
        name: 'Татьяна Ахметгалиева',
        direction: 'Графика, инсталляция, текстиль',
        image: 'https://static.sobaka.ru/images/image/01/79/05/57/_normal.png?v=1709643171',
        bio: 'Татьяна Ахметгалиева — художник-график и автор инсталляций, в которых вышивка и графический жест выходят за пределы плоскости. Родилась в Кемерове, обучалась в Санкт-Петербурге, работает между двумя столицами. Ее дебют состоялся на Уральской биеннале в 2010 году.',
        concept:
            'Использую вышивку как форму памяти и телесного следа, превращая плоскость в пространственный опыт.',
        portfolio: [
            {
                title: 'Любительница кристаллов #2',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsFxaGFnom-bSvXdjccfh1wjBfltLMO9meww&s',
                year: 2012,
            },
            {
                title: 'Стадия куколки',
                image: 'https://avatars.dzeninfra.ru/get-zen_doc/3938527/pub_6233a8ffdaa2462fb7dfb035_6233a903daa2462fb7dfb2f4/scale_1200',
                year: 2013,
            },
        ],
    },
    {
        id: 5,
        name: 'Антонина Баевер',
        direction: 'Видео-арт, инсталляция',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3Jw2bth-n8xv1IHLzuB4UxlYxbulnSVynNA&s',
        bio: 'Антонина Баевер работает с видео, объектами и инсталляциями, критически осмысляя социальные и культурные структуры. Ее ранние проекты были связаны с исследованием институциональных механизмов — от образовательной системы до массовых медиа.',
        concept:
            'Создаю иронично-абсурдные художественные модели будущего, используя реальные социальные сценарии как основу художественного высказывания.',
        portfolio: [
            {
                title: 'Институциональная критика',
                image: 'https://scontent.fkiv6-1.fna.fbcdn.net/v/t1.6435-9/60738536_2338002309590229_8726022481904664576_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=127cfc&_nc_ohc=aHcLMQlCfiQQ7kNvwHDU8Xa&_nc_oc=AdnpSbJcrGVVOHds1kA3ysvkya8glNL3xlMjDRGrQqtn-CxAhsrZBKcT-maYX-m-1KI&_nc_zt=23&_nc_ht=scontent.fkiv6-1.fna&_nc_gid=6ffVcPccwulxnlT3k7C2Zg&oh=00_AfnIB6VaFahBh0GOxvIY4FoeSvHJLlp3D9v5UvpWt50pjg&oe=6974EF84',
                year: 2015,
            },
        
        ],
    },
    {
        id: 6,
        name: 'Андрей Бартенев',
        direction: 'Перформанс, мода, инсталляция',
        image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/4303601/f5cdaeb3-b159-4159-8440-68c961fd908a/220x330',
        bio: 'Андрей Бартенев — один из самых экстравагантных художников России. Его метод — ироничный эпатаж, превращающий искусство в карнавальное зрелище.',
        concept:
            'Работаю на границе искусства, театра и дизайна, превращая самого себя в художественный объект.',
        portfolio: [
            {
                title: 'Карнавальные перформансы',
                image: 'https://cdnstatic.rg.ru/uploads/images/gallery/6c189eb5/1_cdcb61fe.jpg',
                year: 2014,
            },
            {
                title: 'Интерактивные инсталляции',
                image: 'https://api.vladey.net/storage/artwork/11826/regular_preview_image-f3348c47f5157a54fbaa59b9d91a84c6.jpeg',
                year: 2015,
            },
        ],
    },
    {
        id: 7,
        name: 'Константин Батынков',
        direction: 'Живопись, графика',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQixS42q7G1Ia2a4Ll4pgkxMJ1TTQOaDPAAmw&s',
        bio: 'Константин Батынков известен монохромной живописью с «мальчишескими» сюжетами — корабли, самолеты, массовые сцены.',
        concept:
            'Соединяю наивную образность с глубокими культурными и историческими подтекстами.',
        portfolio: [
            {
                title: 'Монохромные корабли',
                image: 'https://optim.tildacdn.com/stor6261-6634-4033-b564-653962323333/-/contain/36x40/center/center/-/format/webp/43792212.jpg.webp',
                year: 2013,
            },
            {
                title: 'Самолеты',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfsZkMvkKBrvtcUSC1Al1vp8bLuY3IKh7rkQ&s',
                year: 2014,
            },
            
        ],
    },
    {
        id: 8,
        name: 'Петр Белый',
        direction: 'Инсталляция, объект',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTn0ZF5mZvlWlqX2f6Pbt7ilXMfrGP5AYdHAA&s',
        bio: 'Петр Белый — художник и куратор, развивающий авторский подход «мемориального моделирования», работая с исчезающей материальной культурой.',
        concept:
            'Развиваю авторский подход «мемориального моделирования», работая с исчезающей материальной культурой.',
        portfolio: [
            {
                title: 'Мемориальные объекты',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRj2vtv06lkl1LYcOW2rrANiskHJmzKiUkkmg&s',
                year: 2014,
            },
            {
                title: 'Пространственные модели',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRL6XmRn6zZ_vguqZSZI14tn-FIpcdnGHRdzw&s',
                year: 2016,
            },
        ],
    },
    {
        id: 9,
        name: 'Сергей Братков',
        direction: 'Фотография, инсталляция',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCTpaQ2AE3hjaQpOBAW1DyOOpNff5DuvvohQ&s',
        bio: 'Сергей Братков работает с фотографией и инсталляцией, через иронию и поэтику исследуя идентичность, милитаризацию и визуальную агрессию общества.',
        concept:
            'Через иронию и поэтику исследую идентичность, милитаризацию и визуальную агрессию общества.',
        portfolio: [
            {
                title: 'Фотографические серии',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6hUcQ1PYlu813pFGoVZq7jro_XDVFc5JwcQ&s',
                year: 2013,
            },
            {
                title: 'Ирония и идентичность',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwln-jMAWShMc3em4QuzgQ0AcXyOr1pRat4Q&s',
                year: 2014,
            },
        ],
    },
    {
        id: 10,
        name: 'Александр Бродский',
        direction: 'Инсталляция, пространственное искусство',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTn0ZF5mZvlWlqX2f6Pbt7ilXMfrGP5AYdHAA&s',
        bio: 'Александр Бродский — художник и архитектор, работающий с хрупкостью памяти и утраченной культурой, создавая тонкие пространственные высказывания.',
        concept:
            'Работаю с хрупкостью памяти и утраченной культурой, создавая тонкие пространственные высказывания.',
        portfolio: [
            {
                title: 'Хрупкость памяти',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaq7sVML1bYhGKJNnIWF9-1Pus0iu8hZxgQw&s',
                year: 2013,
            },
            {
                title: 'Утраченная культура',
                image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFSXpI5O-GzRpZvX9uXaH_0D0bteHWONRLdw&s',
                year: 2015,
            },
        ],
    },
];
const venues = [
    {
        id: 1,
        name: 'Тираспольская картинная галерея',
        type: 'Музей',
        typeCategory: 'museum',
        district: 'Центральный',
        address: 'г. Тирасполь, пер. Набережный, 1',
        howToGet: 'Остановка «Центр», 5 минут пешком от набережной',
        workingHours: 'Вт–Вс 10:00–18:00',
        phone: '+373 533 6-56-96',
        website: 'https://culture.gospmr.org',
        description:
            'Главная художественная институция Тирасполя, специализирующаяся на выставках современной и классической живописи, графики и тематических кураторских проектах. Галерея активно работает с региональными художниками, поддерживает молодые имена и проводит вернисажи, лекции и творческие встречи. Пространство используется как ключевая платформа для художественного диалога и презентации актуальных тенденций в изобразительном искусстве региона.',
        averagePrice: '150 ₽',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQF4tbe9HTvX_pcbfKkUxeu4WBmG1EKZJH9Ww&s',
        svgX: 550,
        svgY: 200,
    },
    {
        id: 2,
        name: 'Историко-краеведческий музей Тирасполя',
        type: 'Музей',
        typeCategory: 'museum',
        district: 'Центральный',
        address: 'г. Тирасполь, ул. 25 Октября, 46',
        howToGet: 'Маршрутки №1, №7 до ул. 25 Октября',
        workingHours: 'Вт–Сб 08:30–17:00',
        phone: '+373 533 9-04-26',
        website: 'https://tirgorsovet.org',
        description:
            'Крупный музейный комплекс, сочетающий историческую экспозицию с временными художественными и мультимедийными проектами. Пространство регулярно используется для фото-выставок, междисциплинарных арт-инициатив и культурно-образовательных программ. Подходит для интеграции современного искусства в исторический контекст города.',
        averagePrice: '100 ₽',
        image: 'https://tourismpmr.org/wp-content/uploads/2021/04/muzej-1-1024x683.jpg',
        svgX: 580,
        svgY: 280,
    },
    {
        id: 3,
        name: 'Галерея на Краснодонской',
        type: 'Галерея',
        typeCategory: 'gallery',
        district: 'Центральный',
        address: 'г. Тирасполь, ул. Краснодонская, 27',
        howToGet: 'Пешком из центра, 7 минут',
        workingHours: 'Ежедневно 10:00–18:00',
        phone: '+373 533 2-84-12',
        website: '',
        description:
            'Камерное выставочное пространство, ориентированное на современную живопись, фотографию и графику. Галерея поддерживает локальных художников, экспериментальные форматы и небольшие кураторские проекты. Часто используется для персональных и тематических экспозиций.',
        averagePrice: '100 ₽',
        image: 'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzQnDYJkAQoRr9l0ghvQVK2Qg7xgs23ZzZ-BeFJEthhGoOwTaaXQ_f0h5mngcvOhrEk47L_RKmQU7hZgMTA1xX6DdEDglk73wKdX9nNceCNfZPYTG9CWbl9OeojdtigmK2VyX2SVg=s1360-w1360-h1020-rw',
        svgX: 620,
        svgY: 150,
    },
    {
        id: 4,
        name: 'Выставочный зал Союза художников ПМР',
        type: 'Галерея',
        typeCategory: 'gallery',
        district: 'Центральный',
        address: 'Бендеры, ул. Коммунистическая, 77',
        howToGet: 'На транспорте до Бендер, потом пешком еще 10 минут',
        workingHours: 'Пн–Пт 11:00–17:00',
        phone: '',
        website: '',
        description:
            'Выставочный зал, представляющий работы профессиональных художников региона. Основной фокус — коллективные выставки, тематические проекты и художественные отчёты. Пространство используется для развития профессионального арт-сообщества.',
        averagePrice: 'Бесплатно',
        image: 'https://pridnestrovie-tourism.com/wp-content/uploads/2025/01/shp-2025_11.jpg',
        svgX: 480,
        svgY: 220,
    },
    {
        id: 5,
        name: 'Выставочная аудитория Екатерининского парка',
        type: 'Галерея',
        typeCategory: 'gallery',
        district: 'Центральный',
        address: 'г. Тирасполь, центральный район',
        howToGet: 'Маршрутки до центра города',
        workingHours: 'Вт–Вс 09:30–18:00',
        phone: '',
        website: '',
        description:
            'Выставочная площадка для временных арт-проектов, форумов и культурных инициатив. Пространство адаптируется под лекции, воркшопы и экспериментальные выставки современного искусства.',
        averagePrice: '120 ₽',
        image: 'https://tourismpmr.org/wp-content/uploads/2023/11/20200910-img_1319-1024x683.jpg',
        svgX: 450,
        svgY: 250,
    },
    {
        id: 6,
        name: 'Городской дом культуры Тирасполя',
        type: 'Арт-центр',
        typeCategory: 'art-center',
        district: 'Центральный',
        address: 'г. Тирасполь, ул. 25 Октября, 54',
        howToGet: 'Общественный транспорт до ул. 25 Октября',
        workingHours: 'Ежедневно 09:00–21:00',
        phone: '',
        website: '',
        description:
            'Многофункциональный культурный центр для проведения перформансов, лекций, кинопоказов и междисциплинарных арт-проектов. Часто используется для масштабных городских культурных программ.',
        averagePrice: '200 ₽',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRC5pBspLjssf1iOsqJ32EVICUHRQ57JintJw&s',
        svgX: 520,
        svgY: 300,
    },
    {
        id: 7,
        name: 'Художественная школа им. С. В. Рахманинова',
        type: 'Арт-центр',
        typeCategory: 'art-center',
        district: 'Центральный',
        address: 'г. Тирасполь, ул. Одесская, 74/1',
        howToGet: 'Маршрутки до ул. Одесская',
        workingHours: 'Пн–Пт 09:00–18:00',
        phone: '',
        website: '',
        description:
            'Образовательное арт-пространство, где проходят студенческие выставки, мастер-классы и художественные презентации. Подходит для образовательных и экспериментальных проектов.',
        averagePrice: 'Бесплатно',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0pnZirn2ZA2rEe2osHZmUWk1aFz92WfxMng&s',
        svgX: 350,
        svgY: 350,
    },
    {
        id: 8,
        name: 'Детская художественная школа',
        type: 'Арт-центр',
        typeCategory: 'art-center',
        district: 'Центральный',
        address: 'г. Тирасполь, ул. Розы Люксембург, 69',
        howToGet: 'Маршрутки до ул. Розы Люксембург',
        workingHours: 'Пн–Сб 09:00–17:00',
        phone: '+373 533 9-31-64',
        website: '',
        description:
            'Культурно-образовательная площадка с регулярными выставками детского и подросткового творчества, арт-мастерскими и тематическими экспозициями.',
        averagePrice: 'Бесплатно',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjh3IX22f9C8BtBs4qe2joydDu_Yi4PBMaFw&s',
        svgX: 320,
        svgY: 380,
    },
    {
        id: 9,
        name: 'Тираспольская крепость',
        type: 'Креативный кластер',
        typeCategory: 'cluster',
        district: 'Исторический район',
        address: 'г. Тирасполь, исторический район',
        howToGet: 'Пешком от центра или маршрутки до старого города',
        workingHours: 'Ср–Вс 10:00–19:00',
        phone: '',
        website: '',
        description:
            'Историко-архитектурный комплекс, используемый как креативное пространство для уличных перформансов, арт-инсталляций и фестивалей под открытым небом. Является ключевой open-air площадкой города.',
        averagePrice: '80 ₽',
        image: 'https://avatars.mds.yandex.net/get-altay/200322/2a0000015b16efa7caa40ba626730eebc054/XL',
        svgX: 280,
        svgY: 420,
    },
];

const events = [
    // Выставки (8-10 событий)
    {
        id: 1,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRg2n1ZPFBUFjD6377Y_PezLv24b100SAUs0Q&s',
        alt: 'Выставка Новые горизонты',
        title: 'Новые горизонты',
        type: 'Выставка',
        genre: 'Современная живопись',
        date: '1 декабря — 20 декабря',
        dateStart: '2025-12-01',
        dateEnd: '2025-12-20',
        price: '500 ₽',
        description:
            'Современные художники Тирасполя представляют свои работы в картинной галерее. Выставка продлится до конца месяца.',
        curator: 'Анна Морозова',
        concept:
            'Выставка "Новые горизонты" исследует трансформацию современного искусства в регионе. Кураторский проект объединяет работы художников разных поколений, демонстрируя эволюцию художественного языка и поиск новых форм выражения. Экспозиция приглашает зрителя к диалогу о будущем искусства и его роли в современном обществе.',
        schedule:
            'Понедельник — выходной\nВторник — воскресенье: 10:00 — 18:00\nПоследняя пятница месяца: 10:00 — 21:00',
        keywords: 'живопись, современное искусство, абстракция',
        popularity: 85,
        artistIds: [1],
        venueId: 1,
    },
    {
        id: 2,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgZdhjYddGMoefm_v6A1qhfDPNVpBXdA7wfQ&s',
        alt: 'Перформанс Границы',
        title: 'Границы',
        type: 'Перформанс',
        genre: 'Скульптура и инсталляция',
        date: '3 декабря, 19:00',
        dateStart: '2025-12-03',
        dateEnd: '2025-12-03',
        price: '800 ₽',
        description:
            'Экспериментальный перформанс, исследующий границы между искусством и реальностью.',
        curator: 'Мария Сидорова',
        concept:
            'Перформанс "Границы" — это исследование физических и метафорических границ в современном мире. Художник создаёт пространство, где зритель становится участником, стирая традиционные границы между сценой и залом, между искусством и жизнью. Проект исследует вопросы идентичности, принадлежности и свободы самовыражения.',
        schedule:
            '3 декабря, 19:00\nПродолжительность: 60 минут\nПосле перформанса — обсуждение с художником',
        keywords: 'перформанс, скульптура, границы',
        popularity: 75,
        artistIds: [3],
        venueId: 2,
    },
    {
        id: 3,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmBh4ygaCKUJnwMyzsSATxrKEs4qZ2Yfmciw&s',
        alt: 'Мастер-класс Современная живопись',
        title: 'Современная живопись',
        type: 'Мастер-класс',
        genre: 'Современная живопись',
        date: '7 декабря, 14:00',
        dateStart: '2025-12-07',
        dateEnd: '2025-12-07',
        price: '1200 ₽',
        description:
            'Образовательный мастер-класс для всех желающих познакомиться с техниками современной живописи.',
        curator: 'Иван Петров',
        concept:
            'Мастер-класс предлагает участникам погрузиться в процесс создания современной живописи. Под руководством опытного художника вы освоите базовые техники абстрактной живописи, работу с цветом и композицией. Занятие подходит как для начинающих, так и для тех, кто хочет расширить свой художественный арсенал.',
        schedule:
            '7 декабря, 14:00 — 17:00\nПродолжительность: 3 часа\nВсе материалы предоставляются',
        keywords: 'мастер-класс, живопись, обучение',
        popularity: 90,
        artistIds: [1],
        venueId: 3,
    },
    {
        id: 4,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-Cy_ubafTv1fEvDoIKlG3bkhCV-unP5qoKw&s',
        alt: 'Выставка Абстракция',
        title: 'Абстракция',
        type: 'Выставка',
        genre: 'Современная живопись',
        date: '5 декабря — 25 декабря',
        dateStart: '2025-12-05',
        dateEnd: '2025-12-25',
        price: '400 ₽',
        description:
            'Коллекция абстрактных работ от ведущих современных художников.',
        curator: 'Елена Волкова',
        concept:
            'Выставка "Абстракция" представляет коллекцию работ, исследующих возможности абстрактного языка в современном искусстве. Экспозиция демонстрирует разнообразие подходов к абстракции — от геометрических композиций до экспрессивных цветовых полей. Каждая работа — это исследование формы, цвета и пространства, приглашающее зрителя к собственным интерпретациям.',
        schedule:
            'Понедельник — выходной\nВторник — воскресенье: 11:00 — 19:00\nКаждую субботу в 15:00 — экскурсия с куратором',
        keywords: 'абстракция, живопись, современное искусство',
        popularity: 80,
        artistIds: [1],
        venueId: 1,
    },
    {
        id: 5,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRR3cz5tMS3jflMDbiDaVmNNkGTeX0vAT2HNg&s',
        alt: 'Инсталляция Пространство',
        title: 'Пространство',
        type: 'Выставка',
        genre: 'Скульптура и инсталляция',
        date: '10 декабря — 5 января',
        dateStart: '2025-12-10',
        dateEnd: '2026-01-05',
        price: '600 ₽',
        description:
            'Масштабная инсталляция, исследующая концепцию пространства в современном искусстве.',
        curator: 'Дмитрий Соколов',
        concept:
            'Инсталляция "Пространство" трансформирует выставочный зал в интерактивную среду, где зритель становится частью художественного произведения. Проект исследует отношения между физическим пространством и восприятием, между архитектурой и телом, между статикой и движением. Инсталляция создаёт условия для нового опыта взаимодействия с пространством.',
        schedule:
            'Понедельник — выходной\nВторник — воскресенье: 10:00 — 18:00\nРекомендуемое время посещения: 30-45 минут',
        keywords: 'инсталляция, пространство, скульптура',
        popularity: 70,
        artistIds: [2],
        venueId: 4,
    },
    {
        id: 6,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyJvT9juhSb_x8lEVxbN-3JCyGaVhJDMLRkQ&s',
        alt: 'Лекция Тенденции искусства',
        title: 'Тенденции искусства',
        type: 'Лекция',
        genre: 'Видео-арт и медиа-искусство',
        date: '12 декабря, 18:00',
        dateStart: '2025-12-12',
        dateEnd: '2025-12-12',
        price: '300 ₽',
        description:
            'Приглашаем на лекцию известного искусствоведа о тенденциях в современном искусстве.',
        curator: 'Дмитрий Соколов',
        concept:
            'Лекция "Тенденции современного искусства" предлагает обзор ключевых направлений и практик в искусстве последних лет. Искусствовед расскажет о развитии цифрового искусства, новых формах инсталляции, актуальных темах и методах работы современных художников. После лекции предусмотрено время для вопросов и дискуссии.',
        schedule:
            '12 декабря, 18:00 — 19:30\nПродолжительность: 90 минут\nПосле лекции — кофе-брейк и обсуждение',
        keywords: 'лекция, тенденции, современное искусство',
        popularity: 65,
        artistIds: [5],
        venueId: 2,
    },
    // Дополнительные выставки
    {
        id: 7,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPkJaF65qRGVIAXl_JfeeOGavr17w02-w9hQ&s',
        alt: 'Выставка Фотография сегодня',
        title: 'Фотография сегодня',
        type: 'Выставка',
        genre: 'Фотография',
        date: '15 декабря — 10 января',
        dateStart: '2025-12-15',
        dateEnd: '2026-01-10',
        price: '350 ₽',
        description:
            'Современная фотография: от документалистики до концептуальных проектов.',
        curator: 'Анна Морозова',
        concept:
            'Выставка представляет работы современных фотографов, исследующих актуальные темы через объектив камеры.',
        schedule: 'Вторник — воскресенье: 11:00 — 19:00',
        keywords: 'фотография, современное искусство, документалистика',
        popularity: 78,
        artistIds: [6],
        venueId: 7,
    },
    {
        id: 8,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfnsPmeDdIWuh6-bWEBXBe0Y36BQ9E8Ti1dg&s',
        alt: 'Выставка Графика и иллюстрация',
        title: 'Графика и иллюстрация',
        type: 'Выставка',
        genre: 'Графика и иллюстрация',
        date: '20 декабря — 15 января',
        dateStart: '2025-12-20',
        dateEnd: '2026-01-15',
        price: '250 ₽',
        description:
            'Коллекция графических работ и иллюстраций от современных мастеров.',
        curator: 'Анна Морозова',
        concept:
            'Экспозиция демонстрирует разнообразие техник графического искусства и современной иллюстрации.',
        schedule:
            'Понедельник — выходной\nВторник — воскресенье: 10:00 — 18:00',
        keywords: 'графика, иллюстрация, рисунок',
        popularity: 72,
        artistIds: [6],
        venueId: 1,
    },
    {
        id: 9,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKiRzaF50fLL_nkzZT6nTzH7iwnpF9eJIyoA&s',
        alt: 'Выставка Видео-арт',
        title: 'Видео-арт: новые медиа',
        type: 'Выставка',
        genre: 'Видео-арт и медиа-искусство',
        date: '1 января — 20 января',
        dateStart: '2026-01-01',
        dateEnd: '2026-01-20',
        price: '450 ₽',
        description: 'Интерактивная выставка видео-арта и медиа-инсталляций.',
        curator: 'Елена Волкова',
        concept:
            'Исследование возможностей видео-арта и новых медиа в современном искусстве.',
        schedule: 'Вторник — воскресенье: 12:00 — 20:00',
        keywords: 'видео-арт, медиа-искусство, интерактивность',
        popularity: 68,
        artistIds: [4],
        venueId: 6,
    },
    {
        id: 10,
        image: 'https://bizar.art/api/media/imgproxy/insecure/fit/500/600/ce/0/KohiAwica1NWYuv-TQHDD?3',
        alt: 'Выставка Скульптура',
        title: 'Современная скульптура',
        type: 'Выставка',
        genre: 'Скульптура и инсталляция',
        date: '5 января — 1 февраля',
        dateStart: '2026-01-05',
        dateEnd: '2026-02-01',
        price: '550 ₽',
        description: 'Выставка скульптурных работ современных мастеров.',
        curator: 'Дмитрий Соколов',
        concept:
            'Экспозиция представляет разнообразие подходов к скульптуре в современном искусстве.',
        schedule:
            'Понедельник — выходной\nВторник — воскресенье: 10:00 — 18:00',
        keywords: 'скульптура, современное искусство, форма',
        popularity: 74,
        artistIds: [3],
        venueId: 4,
    },
    {
        id: 11,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBvslXwvT6H4FzC0_K82quTOf0vsnpk1c5mw&s',
        alt: 'Выставка Живопись и цвет',
        title: 'Живопись и цвет',
        type: 'Выставка',
        genre: 'Современная живопись',
        date: '10 января — 5 февраля',
        dateStart: '2026-01-10',
        dateEnd: '2026-02-05',
        price: '500 ₽',
        description: 'Исследование цвета в современной живописи.',
        curator: 'Иван Петров',
        concept:
            'Выставка посвящена исследованию цвета как основного выразительного средства в живописи.',
        schedule: 'Вторник — воскресенье: 11:00 — 19:00',
        keywords: 'живопись, цвет, современное искусство',
        popularity: 82,
        artistIds: [1],
        venueId: 7,
    },
    // Лекции и дискуссии (5-6 событий)
    {
        id: 12,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM9YiPDUiUv4zHbMNB7tDiTeazQ_Vk1NGjhQ&s',
        alt: 'Лекция История фотографии',
        title: 'История фотографии',
        type: 'Лекция',
        genre: 'Фотография',
        date: '8 декабря, 17:00',
        dateStart: '2025-12-08',
        dateEnd: '2025-12-08',
        price: '200 ₽',
        description:
            'Лекция об истории развития фотографии как вида искусства.',
        curator: 'Анна Морозова',
        concept:
            'Обзорный курс по истории фотографии от первых снимков до современности.',
        schedule: '8 декабря, 17:00 — 18:30',
        keywords: 'лекция, фотография, история',
        popularity: 60,
        artistIds: [6],
        venueId: 2,
    },
    {
        id: 13,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT03a7PgTw_hIET1-Zg7amAmX23JpOFd5aZIg&s',
        alt: 'Дискуссия Искусство и технологии',
        title: 'Искусство и технологии',
        type: 'Лекция',
        genre: 'Видео-арт и медиа-искусство',
        date: '15 декабря, 19:00',
        dateStart: '2025-12-15',
        dateEnd: '2025-12-15',
        price: '250 ₽',
        description:
            'Дискуссия о взаимодействии искусства и современных технологий.',
        curator: 'Елена Волкова',
        concept:
            'Обсуждение влияния технологий на современное искусство и новые формы выражения.',
        schedule: '15 декабря, 19:00 — 20:30',
        keywords: 'дискуссия, технологии, медиа-искусство',
        popularity: 70,
        artistIds: [4],
        venueId: 6,
    },
    {
        id: 14,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1Vz0i99_KVm6kl6EZfKKW-febLOGPsLwHug&s',
        alt: 'Лекция Современная графика',
        title: 'Современная графика',
        type: 'Лекция',
        genre: 'Графика и иллюстрация',
        date: '18 декабря, 16:00',
        dateStart: '2025-12-18',
        dateEnd: '2025-12-18',
        price: '180 ₽',
        description: 'Лекция о техниках и направлениях современной графики.',
        curator: 'Анна Морозова',
        concept:
            'Обзор современных техник графического искусства и иллюстрации.',
        schedule: '18 декабря, 16:00 — 17:30',
        keywords: 'лекция, графика, техники',
        popularity: 58,
        artistIds: [6],
        venueId: 1,
    },
    {
        id: 15,
        image: 'https://www.profguide.io/images/article/a/52/D0jdPTPCi1.webp',
        alt: 'Дискуссия Роль куратора',
        title: 'Роль куратора в современном искусстве',
        type: 'Лекция',
        genre: 'Современная живопись',
        date: '22 декабря, 18:00',
        dateStart: '2025-12-22',
        dateEnd: '2025-12-22',
        price: '220 ₽',
        description:
            'Дискуссия о роли куратора в создании выставок и проектов.',
        curator: 'Дмитрий Соколов',
        concept:
            'Обсуждение кураторских практик и их влияния на восприятие искусства.',
        schedule: '22 декабря, 18:00 — 19:30',
        keywords: 'дискуссия, кураторство, выставки',
        popularity: 55,
        artistIds: [5],
        venueId: 2,
    },
    {
        id: 16,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDn5lfmuP-uSh38q6s2sJSn38_97w6Md7Qbw&s',
        alt: 'Лекция Скульптура 21 века',
        title: 'Скульптура 21 века',
        type: 'Лекция',
        genre: 'Скульптура и инсталляция',
        date: '28 декабря, 17:00',
        dateStart: '2025-12-28',
        dateEnd: '2025-12-28',
        price: '200 ₽',
        description: 'Лекция о развитии скульптуры в современную эпоху.',
        curator: 'Алексей Козлов',
        concept: 'Обзор современных направлений в скульптуре и инсталляции.',
        schedule: '28 декабря, 17:00 — 18:30',
        keywords: 'лекция, скульптура, современность',
        popularity: 62,
        artistIds: [3],
        venueId: 4,
    },
    {
        id: 17,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSknWOmM0RE7ibqBxiKJgC315WdGXf7cnkf0A&s',
        alt: 'Дискуссия Женщины в искусстве',
        title: 'Женщины в современном искусстве',
        type: 'Лекция',
        genre: 'Современная живопись',
        date: '2 января, 19:00',
        dateStart: '2026-01-02',
        dateEnd: '2026-01-02',
        price: '0 ₽',
        description:
            'Бесплатная дискуссия о роли женщин в современном искусстве.',
        curator: 'Мария Сидорова',
        concept:
            'Обсуждение вклада женщин-художниц в развитие современного искусства.',
        schedule: '2 января, 19:00 — 20:30',
        keywords: 'дискуссия, женщины, искусство',
        popularity: 88,
        artistIds: [2],
        venueId: 6,
    },
    // Мастер-классы (3-4 события)
    {
        id: 18,
        image: 'https://px-web-images1.pixpa.com/xB5M4v1pCU1DyOWizUgd3-doew2js6qd_6kvlRFWGEk/rs:fit:1200:0/q:80/aHR0cHM6Ly9waXhwYWNvbS1pbWcucGl4cGEuY29tL2NvbS9hcnRpY2xlcy8xNTU5MjA4NzI0LTk2MTcyNS1kZXBvc2l0cGhvdG9zLTE2NjUwNjg5OC1sLTIwMTVqcGVnLmpwZw==',
        alt: 'Мастер-класс Фотография',
        title: 'Основы фотографии',
        type: 'Мастер-класс',
        genre: 'Фотография',
        date: '5 декабря, 15:00',
        dateStart: '2025-12-05',
        dateEnd: '2025-12-05',
        price: '900 ₽',
        description: 'Практический мастер-класс по основам фотографии.',
        curator: 'Анна Морозова',
        concept: 'Изучение базовых техник фотографии и работы с камерой.',
        schedule: '5 декабря, 15:00 — 18:00',
        keywords: 'мастер-класс, фотография, обучение',
        popularity: 85,
        artistIds: [6],
        venueId: 7,
    },
    {
        id: 19,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqqeFveUP5UsWHjkQDaY5NK8Nw3u5S_CyEfA&s',
        alt: 'Мастер-класс Графика',
        title: 'Техники графики',
        type: 'Мастер-класс',
        genre: 'Графика и иллюстрация',
        date: '10 декабря, 14:00',
        dateStart: '2025-12-10',
        dateEnd: '2025-12-10',
        price: '800 ₽',
        description:
            'Мастер-класс по различным техникам графического искусства.',
        curator: 'Анна Морозова',
        concept: 'Практическое изучение техник графики и иллюстрации.',
        schedule: '10 декабря, 14:00 — 17:00',
        keywords: 'мастер-класс, графика, техники',
        popularity: 78,
        artistIds: [6],
        venueId: 1,
    },
    {
        id: 20,
        image: 'https://photo-study.ru/files/styles/1000w/public/events/di_2.jpg?itok=6VSP0N25',
        alt: 'Мастер-класс Цифровое искусство',
        title: 'Цифровое искусство',
        type: 'Мастер-класс',
        genre: 'Видео-арт и медиа-искусство',
        date: '14 декабря, 16:00',
        dateStart: '2025-12-14',
        dateEnd: '2025-12-14',
        price: '1000 ₽',
        description: 'Мастер-класс по созданию цифрового искусства.',
        curator: 'Елена Волкова',
        concept: 'Изучение инструментов и техник цифрового искусства.',
        schedule: '14 декабря, 16:00 — 19:00',
        keywords: 'мастер-класс, цифровое искусство, медиа',
        popularity: 80,
        artistIds: [4],
        venueId: 6,
    },
    {
        id: 21,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwucbrlCqNy5twSIxzaa_9pfUzUnixDc4-pg&s',
        alt: 'Мастер-класс Скульптура',
        title: 'Работа с материалами',
        type: 'Мастер-класс',
        genre: 'Скульптура и инсталляция',
        date: '20 декабря, 13:00',
        dateStart: '2025-12-20',
        dateEnd: '2025-12-20',
        price: '1100 ₽',
        description:
            'Мастер-класс по работе с различными материалами в скульптуре.',
        curator: 'Алексей Козлов',
        concept: 'Практическое изучение работы с материалами в скульптуре.',
        schedule: '20 декабря, 13:00 — 16:00',
        keywords: 'мастер-класс, скульптура, материалы',
        popularity: 75,
        artistIds: [3],
        venueId: 4,
    },
    // Перформансы (2-3 события)
    {
        id: 22,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXpQlaRN-T_9e9_d84iwCd5aJnKGZbmjnkcw&s',
        alt: 'Перформанс Время',
        title: 'Время',
        type: 'Перформанс',
        genre: 'Видео-арт и медиа-искусство',
        date: '25 декабря, 20:00',
        dateStart: '2025-12-25',
        dateEnd: '2025-12-25',
        price: '750 ₽',
        description: 'Экспериментальный перформанс о восприятии времени.',
        curator: 'Елена Волкова',
        concept:
            'Исследование концепции времени через перформативное искусство.',
        schedule: '25 декабря, 20:00\nПродолжительность: 45 минут',
        keywords: 'перформанс, время, медиа-искусство',
        popularity: 73,
        artistIds: [4],
        venueId: 6,
    },
    {
        id: 23,
        image: 'https://www.akcent.uk/uploads/article/image/9384/v780x400_1.png',
        alt: 'Перформанс Тело',
        title: 'Тело и пространство',
        type: 'Перформанс',
        genre: 'Скульптура и инсталляция',
        date: '30 декабря, 19:00',
        dateStart: '2025-12-30',
        dateEnd: '2025-12-30',
        price: '850 ₽',
        description:
            'Перформанс, исследующий отношения между телом и пространством.',
        curator: 'Алексей Козлов',
        concept:
            'Исследование телесности и пространственных отношений через перформанс.',
        schedule: '30 декабря, 19:00\nПродолжительность: 50 минут',
        keywords: 'перформанс, тело, пространство',
        popularity: 77,
        artistIds: [3],
        venueId: 2,
    },
    // Кинопоказы (2 события)
    {
        id: 24,
        image: 'https://vichugskie.ru/wp-content/uploads/2018/05/YnLUKM6rrn5y4pWla_B7eg-930x450.jpg',
        alt: 'Кинопоказ Арт-хаус',
        title: 'Арт-хаус кино: современные режиссёры',
        type: 'Кинопоказ',
        genre: 'Видео-арт и медиа-искусство',
        date: '12 января, 19:30',
        dateStart: '2026-01-12',
        dateEnd: '2026-01-12',
        price: '400 ₽',
        description: 'Показ фильмов современных режиссёров арт-хауса.',
        curator: 'Дмитрий Соколов',
        concept: 'Серия показов фильмов, исследующих границы киноискусства.',
        schedule: '12 января, 19:30\nПродолжительность: 2 часа',
        keywords: 'кино, арт-хаус, режиссура',
        popularity: 71,
        artistIds: [5],
        venueId: 5,
    },
    {
        id: 25,
        image: 'https://office-news.ru/wp-content/uploads/2023/09/sok-kinopokaz.jpg',
        alt: 'Кинопоказ Документальное кино',
        title: 'Документальное кино об искусстве',
        type: 'Кинопоказ',
        genre: 'Фотография',
        date: '18 января, 18:00',
        dateStart: '2026-01-18',
        dateEnd: '2026-01-18',
        price: '350 ₽',
        description: 'Показ документальных фильмов о художниках и искусстве.',
        curator: 'Анна Морозова',
        concept:
            'Серия документальных фильмов, рассказывающих о жизни и творчестве художников.',
        schedule: '18 января, 18:00\nПродолжительность: 2.5 часа',
        keywords: 'кино, документалистика, искусство',
        popularity: 69,
        artistIds: [6],
        venueId: 5,
    },
];
